### ISSUE TITLE
Hackage shows no public modules

### ISSUE THREAD

**Issue by kozross** [sordina/churros#1]
I assume this is unintentional?

**Comment by sordina** [comment]
Yes, that's unintentional! Thanks for the heads up!

**Comment by sordina** [comment]
@kozross

I'm probably missing something obvious, but is there additional config required to mark them public?

Shouldn't the exposed modules field achieve this?

```haskell
library churros-lib
  import: churros-dependencies
  hs-source-dirs:   src
  exposed-modules:
    Control.Churro,
    Control.Churro.Types,
    Control.Churro.Prelude,
    Control.Churro.Transport,
    Control.Churro.Transport.Chan
```

**Comment by sordina** [comment]
Looks like I had named the library in the cabal file. Fixed!
