### ISSUE TITLE
Generalize sources

### ISSUE THREAD

**Issue by kozross** [sordina/churros#12]
`sources` is currently defined as so:

```haskell
sources :: (Transport t, Monoid a) => [Source a t o] -> Source () t o
```
Is there any reason why it can't be generalized to this?

```haskell
sources :: (Transport t, Monoid a, Foldable f) => f (Source a t o) -> Source a t o
```

Given that `()` is (trivially) a `Monoid`, this makes `sources_ = sources` a valid definition (and can also be generalized similarly).

**Comment by sordina** [comment]
Great thanks! It would be good if you could get a warning for insufficiently general type signatures somehow...

**Comment by kozross** [comment]
That's not possible in general. The best way (I've found) is to write the definition first, then add a signature full of holes. If you're not doing anything too tricksy, you can get quite general signatures auto-inferred that way. However, this doesn't always work, since some generalizations might not be purely down to giving general enough types: for instance, if you use lists everywhere, GHC won't necessarily be able to figure out that you could use any `Foldable`, since that may require rewriting.

**Comment by sordina** [comment]
Yeah, that's true, but it would be a nice HLS hint.

**Comment by sordina** [comment]
```haskell
sources :: (Transport t, Foldable f, Traversable f) => f (Churro a t Void i) -> Churro () t Void i
sources ss = sourceIO \cb -> do
    asyncs <- mapM (\s -> run $ s >>>> sinkIO cb) ss
    (_, r) <- waitAny (toList asyncs)
    return r
```

Needed the extra Foldable constraint to allow use of waitAny.

**Comment by kozross** [comment]
`Traversable` implies `Foldable`, so that can be simplified a bit. Not really an issue, but makes for a shorter signature.

Also, you could produce a result of type `a` by waiting on all the asyncs, then jamming them together using `<>`.

**Comment by sordina** [comment]
Oh yes, of course!

**Comment by sordina** [comment]
That's a good idea. I actually guess there are some bugs in this implementation since each source could potentially yield a Nothing.

**Comment by sordina** [comment]
I think this is a correct implementation:

```haskell

sources' :: (Transport t, Traversable f, Monoid a) => f (Churro a t Void o) -> Churro a t Void o
sources' ss = buildChurro \_i o -> do
    cs <- mapM runChurro ss
    finally' (mapM_ (\(_,_,a) -> cancel a) cs) do
        as <- for cs \(_i,o',a) -> do
            async do
                yankAll' o' \v -> do
                    case v of
                        Nothing -> return ()
                        Just x  -> yeet o (Just x)
                wait a
        r <- foldMap' wait as
        yeet o Nothing
        return r
```

**Comment by sordina** [comment]
Also, thanks so much for your feedback on this library. Please let me know if there's anything you'd like added to make it more useful for you!

**Comment by kozross** [comment]
You're very welcome - I'm just going through it, calling things as I spot them.

**Comment by sordina** [comment]
I've generalised sources and a few other methods now, so should be able to close this issue.

Another gernalisation that's still pending is having some functions polymorphic over multiple transport types. This allows for switching transport for different sections of the graph such as with the new `Latest` transport, or making sources block in certain situations. This does once again make the instances a bit tricky.
