### ISSUE TITLE
Changelog has a placeholder date

### ISSUE THREAD

**Issue by kozross** [sordina/churros#2]
[As per here](http://hackage.haskell.org/package/churros-0.1.0.2/changelog).

**Comment by sordina** [comment]
Thanks again @kozross updating.

**Comment by sordina** [comment]
Fixed: http://hackage.haskell.org/package/churros-0.1.0.3/changelog

**Comment by sordina** [comment]
Been a while since I published a package and making silly mistakes... Thanks @kozross
