### ISSUE TITLE
Generalize to (MonadIO m) instead of IO

### ISSUE THREAD

**Issue by kozross** [sordina/churros#9]
This is quite doable, and while it does mean carting around _another_ type parameter, it's an increase in flexibility at really no cost.

**Comment by sordina** [comment]
This one is a bit trickier since a lot of the async callbacks depend on IO and I'd like to avoid diving into unlift style dependencies for at least a while.

**Comment by kozross** [comment]
You can just use `liftIO` in those cases, surely? I can't imagine the callbacks have `IO` in a negative position.

**Comment by sordina** [comment]
I'd have to double check the positions but some of the higher-order functions could potentially have the issue. I'll check, and if it's simple to generalise then no reason not to!

**Comment by kozross** [comment]
The only thing that'd pose a problem is cases where you have `IO` in the negative (so something like a function argument typing as `IO a -> b`), which seems a bit unlikely.

**Comment by sordina** [comment]
What about the following?

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/92299/96329129-c539c080-1095-11eb-9f14-33592fa8b095.png">

Or would you keep the callback in IO?

**Comment by kozross** [comment]
You might as well do it like:

```haskell
buildChurro' cb = Churro . liftIO $ do ...
```

You could also generalize the `Transport` functions to rely on `MonadIO m` as a method constraint.

**Comment by sordina** [comment]
But what about the async call?

**Comment by kozross** [comment]
Can't you just `liftIO` the result of the call? `liftIO . async :: (MonadIO m) => IO a -> m (Async a)`. The callback itself would have to stay in `IO` - exactly the 'negative position' problem I was worried about.

**Comment by sordina** [comment]
Yes, the callback is what I was referring to.

**Comment by sordina** [comment]
This makes it tricky to use runChurro inside buildChurro which is a pattern I've adopted.

Let me know if you have any ideas. I'm not too worried about leaving it all in IO since the user can always call liftIO themselves if they need to correct?

![image](https://user-images.githubusercontent.com/92299/96330600-21a2dd00-10a2-11eb-95b4-2dd1da938a76.png)

**Comment by sordina** [comment]
Here's a WIP PR: #11

**Comment by kozross** [comment]
As a non-expert on async anything, I'm not sure if I can offer much. Given the non-triviality of this change (on further examination), and also my lack of knowledge here, maybe keeping with `IO` for now is the best call.

**Comment by sordina** [comment]
There is a lifted-async package: https://hackage.haskell.org/package/lifted-async that makes these kind of things easier, but I think I'll keep things simple for now until someone expresses a need. Thanks for discussing this!
